### ISSUE TITLE
有没有实现对 rocketmq jdbc存储事务的实现

### ISSUE THREAD

**Issue by 1042904326** [kuangye098/rocketmq#1]

**Comment by kuangye098** [comment]
rocketmq最初的版本确实把事务状态存储在mysql里面，但是性能差点，后来改用类似于数据库的redolog以及tranlog日志机制来实现事务状态存储，性能非常不错。

**Comment by 1042904326** [comment]
可是根据这为大神所描述https://github.com/YunaiV/Blog/blob/master/RocketMQ/1011-RocketMQ%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%EF%BC%9A%E4%BA%8B%E5%8A%A1%E6%B6%88%E6%81%AF.md，而且现在转移到apache下面，里面是没有事务实现的，仅仅存在的只有几个JDBC事务实现的存储bean，大神 能不能了解了解你对这个的看法

**Comment by kuangye098** [comment]
说的不错，因为实际上官方说用自定义磁盘文件做事务存储，可能会导致系统脏页过多，这个实际上没有我们没有阿里的运营数据，不能做过多的验证，根据自己的业务量来看，可能影响并不大。基于数据库实现事务存储，那将会简单的多。这个需要根据具体的测试实现，等我有时间，我看把基于mysql实现的事务处理也加入，经过实际测试和运营测试综合来判断那种情况好。

**Comment by 1042904326** [comment]
恩，大神有没有考虑过在apache rocketmq上面进行更改

**Comment by kuangye098** [comment]
我肯定现在在这个分支改，测试通过直接合并到apache rocketmq上，我这个版本和apache rocketmq版本差别目前很少。

**Comment by 1042904326** [comment]
恩  是的，我前二天试着把你更改的记录放在apache rocketmq上，可是存在一些问题，不知道有哪些地方需要注意的，跑起来没有statetable文件记录，只有redolog文件

**Comment by kuangye098** [comment]
改动主要是broker中的store里面。。你可以对比下文件，就8个左右吧，增加了2个左右的文件，多看看生成的日志，很容易排错的。

**Comment by 1042904326** [comment]
恩恩，行 到时有问题再请教你，能不能加个QQ1042904326

**Comment by weir2010** [comment]
事务你们是怎么处理的保存在文件还是数据库？
